name: 'Build map templates'

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'boundaries-collection/**'
      - 'brownfield-land-collection/**'
      - 'dataset-collection/**'
      - 'organisation-dataset/**'
    branches-ignore:
      - '**'
  workflow_dispatch:

env:
  GITHUB_ACTOR_EMAIL: ${{ secrets.GITHUB_ACTOR_EMAIL }}
  GITHUB_ACTOR_TOKEN: ${{ secrets.GITHUB_ACTOR_TOKEN }}
  GITHUB_ACTOR_USERNAME: ${{ secrets.GITHUB_ACTOR_USERNAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Setup git
      run: |
        git config user.email "${GITHUB_ACTOR_EMAIL}"
        git config user.name "${GITHUB_ACTOR_USERNAME}"
        git remote set-url origin https://${GITHUB_ACTOR_USERNAME}:${GITHUB_ACTOR_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        git checkout master
    - name: Install dependencies
      run: make init
    - run: make build_prod
    - name: Commit files
      run: |
        git add docs/ brownfield-land-collection/ boundaries-collection/ dataset-collection/ organisation-dataset/
        git diff --quiet && git diff --staged --quiet || (git commit -m "$(date +%F): Build map templates"; git push origin master)
